#localiza as informações essenciais do nosso projeto, por exemplo, configurações e regras gerais

"""
Django settings for copnetflix project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# armazena o local onde o projeto está localizado
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

#armezena a chave de segurança do projeto e é responsável por gerenciar todos os aspectos de segurança
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-lq5+3or-vug_c^cg=x1k4k^!l2tq%!l*63k3a-yz-3@i)5k@iv'

#atualiza de forma automática as novas informações
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#lista de hosts que serão permitidos
ALLOWED_HOSTS = []


# Application definition
#aplicativos instalados no site
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'filme'
]

#processos de "meio de caminho" que o django já lida (inclui: CSRF, autenticação, segurança e gerenciamento de sessão do usuário)
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
#define o arquivo que contém o link que comanda o site (quais links ficarão disponíveis)
ROOT_URLCONF = 'copnetflix.urls'

#define o local dos arquviso HTML
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

#configuração do servidor
WSGI_APPLICATION = 'copnetflix.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

#definição do banco de dados
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

#configuração dos validadores de senha
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

#configuração do idioma e fuso horário (seu padrão é o inglês)

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Indica a localização dos arquivos de imagens do site(CSS e JavaScript)
STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

# Define a chave primária para as tabelas do nosso banco de dados
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
